export default {
  "RobotoBlackItalic": require("./Roboto-BlackItalic.ttf"),
  "RobotoBlack": require("./Roboto-Black.ttf"),
  "RobotoBoldItalic": require("./Roboto-BoldItalic.ttf"),
  "RobotoBold": require("./Roboto-Bold.ttf"),
  "RobotoCondensedBoldItalic": require("./RobotoCondensed-BoldItalic.ttf"),
  "RobotoCondensedBold": require("./RobotoCondensed-Bold.ttf"),
  "RobotoCondensedItalic": require("./RobotoCondensed-Italic.ttf"),
  "RobotoCondensedLightItalic": require("./RobotoCondensed-LightItalic.ttf"),
  "RobotoCondensedLight": require("./RobotoCondensed-Light.ttf"),
  "RobotoItalic": require("./Roboto-Italic.ttf"),
  "RobotoLightItalic": require("./Roboto-LightItalic.ttf"),
  "RobotoLight": require("./Roboto-Light.ttf"),
  "RobotoMediumItalic": require("./Roboto-MediumItalic.ttf"),
  "RobotoMedium": require("./Roboto-Medium.ttf"),
  "RobotoRegular": require("./Roboto-Regular.ttf"),
  "RobotoThinItalic": require("./Roboto-ThinItalic.ttf"),
  "RobotoThin": require("./Roboto-Thin.ttf"),
};
